'''
Question Description :-

Find the Difference


Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
    Input:
        s = "abcd"
        t = "abcde"
    Output:
            e
    Explanation:
        'e' is the letter that was added.
'''
def findTheDifference(s, t):
    dt = {}
    for x in s:
        if x in dt:
            dt[x] += 1
        else:
            dt[x] = 1

    for x in t:
        if x in dt and dt[x] > 0:
            dt[x] -= 1
        else:
            return x
             

print(findTheDifference('abcd','abcde'))

'''
Optimal Solution :-

def findTheDifference(s,t):
    for i in range(97,97+26):
        if s.count(chr(i))!=t.count(chr(i)):
            return chr(i)
'''